//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrogProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public System.Guid VoucherID { get; set; }
        public string UserID { get; set; }
        public string EventName { get; set; }
        public int Quantity { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string SecondPhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual eventdetail eventdetail { get; set; }
    }
}
